#数据库配置信息
spring:
  datasource:
    username: root
    password: syl123456
    url: jdbc:mysql://localhost:3306/o2o?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#    master:
#      username: root
#      password: syl123456
#      url: jdbc:mysql://localhost:3306/o2o?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    slave:
#      username: root
#        password: syl123456
#        url: jdbc:mysql://localhost:3306/o2o?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#        driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /templates
      suffix: .html




  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 20MB



# 加载mybaties文件
mybatis:
  mapper-locations: classpath:mapping/*Dao.xml
  type-aliases-package: com.sunshy.o2o.entity





#server:
#  servlet:
#    context-path: /o2o





logging:
  level:
    com:
      sunshy:
        o2o:
          mapper: debug
